food/urls.py
from django.urls import path
from food import views 

app_name = 'food'

urlpatterns = [

    #http://127.0.0.1:8000/food/home
    path('home/', views.HomeFunctionView, name='home'),
    #path('home/<str:user_types>', views.HomeClassView.as_view(), name='home'),

    #http://127.0.0.1:8000/food/detail/1/
    path('detail/<int:item_id>/', views.DetailFunctionView, name='detail'),
    #path('detail/<int:pk>/', views.DetailClassView.as_view(), name='detail'),

    #http://127.0.0.1:8000/food/add/
    #path('add/',views.CreateFoodItemFunctionView,name='add'),
    path('add/',views.CreateFoodItemClassView.as_view(),name='add'), 

    #http://127.0.0.1:8000/food/update/1/
    path('update/<int:item_id>/', views.UpdateFoodItemFunctionView, name='update'),

    #http://127.0.0.1:8000/food/delete/1
    path('delete/<int:item_id>/', views.DeleteFoodItemFunctionView, name='delete'),
]


mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from users import views as UserViews

from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('food/', include('food.urls')),
    path('register/', UserViews.RegisterFunctionView, name='register'),
    path('login/', UserViews.LoginFunctionView, name='login'),
    path('logout/', UserViews.LogoutFunctionView, name='logout'),
    path('profile/', UserViews.ProfileFunctionView, name='profile'),

]

urlpatterns += [] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

food/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
# ---------------------------------------------------------------------------------------------- 

#food item model
#--------------------------------------------------------------------------------------------------
class FoodItemsModel(models.Model):
    prod_code = models.IntegerField(default=100)
    restaurant_owner = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        default=1
    )
    admin = models.CharField(max_length=50, null=True)
    item_name = models.CharField(max_length=100)
    item_description = models.CharField(
        max_length=500,
        default="Lorem, ipsum dolor sit amet consectetur adipisicing elit. Explicabo magni, nihil assumenda sit praesentium repellendus autem culpa aliquid sequi beatae eveniet voluptatum exercitationem a aspernatur, illo placeat fugiat ducimus voluptas."
    )
    item_price = models.IntegerField()
    item_image = models.CharField(
        max_length=500,
        default="https://cdn.dribbble.com/userupload/22570626/file/original-379b4978ee41eeb352e0ddacbaa6df96.jpg"
    )

    def __str__(self):
        return str((self.item_name, self.item_price))
    


# log History model
#--------------------------------------------------------------------------------------------------------
class LogHistoryModel(models.Model):       #firs model is object of class and second model is structure
    log_username = models.CharField(max_length=50)
    log_prod_code = models.IntegerField(default=100)
    log_item_name = models.CharField(max_length=100)
    log_operation_type = models.CharField(max_length=50)

    def __str__(self):
        return str(
            {
                self.log_username,
                self.log_prod_code,
                self.log_item_name,
                self.log_operation_type
            }
        )


food/forms.py
from django import forms
from food.models import FoodItemsModel

class FoodItemsForm(forms.ModelForm):
    class Meta:
        model = FoodItemsModel
        fields = ['prod_code','item_name','item_description','item_price','item_image']

food/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from food.models import FoodItemsModel, LogHistoryModel
from food.forms import FoodItemsForm
from django.views.generic.list import ListView
from django.views.generic.detail import DetailView
from django.views.generic.edit import CreateView
from django.urls import reverse_lazy



# Create your views here.
# ---------------------------------------------------------------------------------------------

# function based home view
# ---------------------------------------------------------------------------------------------
def HomeFunctionView(request):
    if request.user.is_authenticated and request.user.profilemodel.user_types == "ADMIN":
        item_list = FoodItemsModel.objects.all()

    elif request.user.is_authenticated and request.user.profilemodel.user_types == "CUSTOMER":
                item_list = FoodItemsModel.objects.all()

    elif request.user.is_authenticated and request.user.profilemodel.user_types == "RESTAURANT":
        item_list = FoodItemsModel.objects.filter(restaurant_owner=request.user.id)

    else:
        item_list = FoodItemsModel.objects.all()

    context = {
        "item_list": item_list
    }
   
    return render(request, "food/home.html", context)


#Class based home view
#------------------------------------------------------------------------------------------------
class HomeClassView(ListView):
    model = FoodItemsModel
    context_object_name = "item_list"
    template_name = "food/home.html"



# function based detail view
# ---------------------------------------------------------------------------------------------
def DetailFunctionView(request, item_id):
    item = FoodItemsModel.objects.get(id=item_id)
    object_lh=LogHistoryModel.objects.filter(
         log_prod_code = item.prod_code
    )
   
    context = {
        'item': item,
        'object_lh': object_lh
    }
   
    return render(request, "food/detail.html", context)


#Class based detail view
#----------------------------------------------------------------------------------------------
class DetailClassView(DetailView):
    model = FoodItemsModel
    context_object_name = 'item'
    template_name = "food/detail.html"


# function based create item view
# ---------------------------------------------------------------------------------------------
def CreateFoodItemFunctionView(request):
    form = FoodItemsForm(request.POST or None)

    if form.is_valid():
        form.save()
        return redirect("food:home")
   
    context = {
        'form': form
    }
   
    return render(request, "food/food-items-form.html", context)

#Class based create item view
#--------------------------------------------------------------------------------------------------
class CreateFoodItemClassView(CreateView):
    model = FoodItemsModel
    fields = ['prod_code','restaurant_owner','item_name','item_description','item_price','item_image']
    template_name = "food/food-items-form.html"
    success_url = reverse_lazy("food:home")

    def form_valid(self, form):
        form.instance.admin = self.request.user.username
        
        object_log_history = LogHistoryModel(
             log_prod_code = form.instance.prod_code,               #self.request.POST.get('prod_code')
             log_username = self.request.user.username,
             log_item_name = form.instance.item_name,               #self.request.POST.get('item_name')
             log_operation_type = 'created',
        )
        object_log_history.save()

        return super().form_valid(form)


# function based update item view
# ---------------------------------------------------------------------------------------------
def UpdateFoodItemFunctionView(request, item_id):
    item = FoodItemsModel.objects.get(id=item_id)
    form = FoodItemsForm(request.POST or None, instance=item)
   
    context = {
        'form': form
    }
   
    if form.is_valid():
        form.save()
        
        object_log_history = LogHistoryModel(
             log_prod_code = form.instance.prod_code,               #self.request.POST.get('prod_code')
             log_username = request.user.username,
             log_item_name = form.instance.item_name,               #self.request.POST.get('item_name')
             log_operation_type = 'updated',
        )
        object_log_history.save()

        return redirect('food:detail', item_id=item_id)
   
    return render(request, "food/food-items-form.html", context)


# function based delete item view
# ---------------------------------------------------------------------------------------------
def DeleteFoodItemFunctionView(request, item_id):
    item = FoodItemsModel.objects.get(id=item_id)
   
    context = {
        'item': item
    }
   
    if request.method == 'POST':
        object_log_history = LogHistoryModel(
             log_prod_code = item.prod_code,               #self.request.POST.get('prod_code')
             log_username = request.user.username,
             log_item_name = item.item_name,               #self.request.POST.get('item_name')
             log_operation_type = 'deleted',
        )
        object_log_history.save()

        
        item.delete()
        return redirect('food:home')
   
    return render(request, "food/item-delete.html", context)

food/templates/food/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
    <!-- <link rel="stylesheet" href="{% static 'food/style.css' %}"> -->
</head>
<body>
    <nav class="navbar navbar-dark bg-dark">
      <a href="{% url 'food:home' %}" class="navbar-brand"> Exortillo </a>

      <div class="navbar">
       
        {% if user.is_authenticated %}

            {% if user.profilemodel.user_types == 'ADMIN' %}
              <a href="{% url 'food:add' %}" class="nav-item nav-link btn btn-dark">
                Add Item
              </a>
            {% endif %}

            <a href="{% url 'profile' %}" class="nav-item nav-link btn btn-dark">
              Profile
            </a>

            <a href="{% url 'logout' %}" class="nav-item nav-link btn btn-dark">
              Logout
            </a>

        {% else %}

            <a href="{% url 'register' %}" class="nav-item nav-link btn btn-dark">
              Sign Up
            </a>

            <a href="{% url 'login' %}" class="nav-item nav-link btn btn-dark">
              Login
            </a>

        {% endif %}

      </div>
    </nav>

    {% if messages %}
      {% for message in messages %}
        <div class="alert alert-{{ message.tags }}">{{ message }}</div>
      {% endfor %}
    {% endif %}
   
    {% block body %}
    {% endblock %}
                                                 
</body>
</html>

food/templates/food/detail.html
{% extends 'food/base.html' %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
   
    {% block body %}

    <div class="row mt-5">
        <div class="col-md-2 offset-md-1">
            <img
                height="150px"
                width="250px"
                class="card"
                src="{{ item.item_image }}"
            >
        </div>

        <div class="col-md-4 offset-md-1">
            <h1
                style="
                    font-style: italic;
                "
            >
                {{ item.item_name }}
            </h1>

            <h2
                style="
                    font-style: italic;
                    font-size: 1.3rem;
                    text-align: justify;
                "
            >
                {{ item.item_description }}
            </h2>

            <h3>
                ${{ item.item_price }}
            </h3>
        </div>

        <div class="col-md-3 offset-md-1">

            {% if user.is_authenticated %}

                {% if user.profilemodel.user_types == "CUSTOMER" %}
                   
                    <a
                        href="#"
                        style="width:80px"
                        class="btn btn-warning"
                    >
                        Cart
                    </a>

                    <a
                        href="#"
                        style="width:80px"
                        class="btn btn-success"
                    >
                        Back
                    </a>

                {% elif user.profilemodel.user_types == "RESTAURANT" %}
                   
                    <a
                        href="{% url 'food:update' item.id %}"
                        style="width:80px"
                        class="btn btn-warning"
                    >
                        Edit
                    </a>

                    <a
                        href="#"
                        style="width:80px"
                        class="btn btn-success"
                    >
                        Back
                    </a>

                {% elif user.profilemodel.user_types == "ADMIN" %}
                    <a
                        href="{% url 'food:update' item.id %}"
                        style="width:80px"
                        class="btn btn-warning"
                    >
                        Edit
                    </a>

                    <a
                        href="{% url 'food:delete' item.id %}"
                        style="width:80px"
                        class="btn btn-danger"
                    >
                        Delete
                    </a>

                    <a
                        href="#"
                        style="width:80px"
                        class="btn btn-success"
                    >
                        Back
                    </a>
               
                {% endif %}

            {% endif %}
           
        </div>
    </div>

    <!-- red: records -->
    
    {% if user.is_authenticated %}

    {% if user.profilemodel.user_types == 'RESTAURANT' or user.profilemodel.user_types == 'ADMIN' %}

    {% for obj in object_lh %}

    <div
        class="row mb-1">

        <div
            class="col-md-8
                offset-md-2
                bg-danger
                text-white">

                <div
                    class="row">

                    <div
                        class="col-md-3
                            text-left">

                        {{ obj.log_username }}
                    </div>

                    <div
                        class="col-md-3
                            text-left">

                        {{ obj.log_prod_code }}
                    </div>

                    <div
                        class="col-md-3
                            text-left">

                        {{ obj.log_item_name }}
                    </div>

                    <div
                        class="col-md-3
                            text-left">

                        {{ obj.log_operation_type }}
                    </div>
                </div>
        </div>

        <div
            class="col-md-2">
           
        </div>

    </div>

    {% endfor %}

    {% endif %}

    {% endif %}

    {% endblock %}
</body>
</html>

food/templates/food/food-items-form.html
{% extends 'food/base.html' %}

{% block body %}

<form method="POST">
    {% csrf_token %}

    <br><label>Product Code: </label><br>
    {{ form.prod_code }}

    <br><label>Restaurant Owner: </label><br>
    {{ form.restaurant_owner }}

    <br><label>Item Name: </label><br>
    {{ form.item_name }}

    <br><label>Item Description: </label><br>
    {{ form.item_description }}

    <br><label>Item Price: </label><br>
    {{ form.item_price }}

    <br><label>Product Image: </label><br>
    {{ form.item_image}}

    <button type="submit">save</button>
</form>

{% endblock %}

food/templates/food/home.html
{% extends 'food/base.html' %}

<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Document</title>
  </head>
  <body>

    {% block body %}

    {% for item in item_list %}

        <div class="row mt-5">
            <div class="col-md-3 offset-md-2">
                <img
                    src="{{ item.item_image }}"
                    class="card"
                    height="135px"
                    width="230px"
                >
            </div>

            <div class="col-md-4">
                <h3 style="font-size: 1.5rem;">{{ item.item_name }}</h3>
                <h5 style="font-style: italic; font-size: 1rem;">{{ item.item_description }}</h5>
                <h6>{{ item.item_price }}</h6>
                <h6 style="font-style: italic;">restaurant owner:{{ item.restaurant_owner }}</h6>
                <h6 style="font-style: italic;">admin:{{ item.admin }} </h6>
            </div>

            <div class="col-md-3">
             
              {% if user.is_authenticated %}

                <a href="{% url 'food:detail' item.id %}" class="btn btn-success" style="width:100px">
                  Details
                </a>

              {% else %}

                <a href="{% url 'login' %}" class="btn btn-danger" style="width:100px">
                  Details
                </a>
               
              {% endif %}
               
            </div>
        </div>

    {% endfor %}

    {% endblock %}

  </body>
</html>

food/templates/food/item-delete.html
{% extends 'food/base.html' %}

 {% block body %}

<form method="POST">
    {% csrf_token %}
    <h1>Are you sure you want to delete{{  item.item_name }}</h1>
    <button type="sybmit">yes</button>
    <a href="{%  url 'food:detail' item.id %}">No</a>
</form>

  {% endblock %} 